### ISSUE TITLE
Calculations are wrong -- somewhere

### ISSUE THREAD

**Issue by gcamp** [florentchandelier/WealthManagement#5]
Trying out the calculator, there's clearly something wrong with the calculation. 

Smith Manoeuvre is a leveraging strategy. Leveraging increase gains but also increase losses. So trying out a scenario with losses on investments, we should see a results that's worst than a regular mortgage. 

Assuming a 0% dividend yield and a -2% growth on the portfolio, I still get improvements over the regular mortgage. Tax credit can't transform a loss into a gain (and even then, since dividend yield is non-existant, the qc limitation should make the tax credit at 0$).

**Comment by gcamp** [comment]
Forgot to say : with these variables, I was getting my mortgage done 8 years before a comparable 25y mortgage

**Comment by florentchandelier** [comment]
Thanks for the feedback. I have never tried with a negative return.
Did you investigate a little bit the code to see where the error would be ?
Did you see any awkward behavior(s) with positive, non-zero returns ?

**Comment by gcamp** [comment]
Results seems normal with positive 'regular' values but I'm not so confident now that I get about the same result with other values!

Didn't check the code too much but I plan to do it in the future. Never done R, so it might take a while to get used to it.

**Comment by florentchandelier** [comment]
Thx for the effort. I will try to look at it next week.

A 2016 plan is to recode the thing in Python so it could be delivered to the community in form of a web app. Wanna help ?

**Comment by gcamp** [comment]
I would choose something else than Python but yep I could help! I don’t have a lot of free time to code but I can put an hour or two a week.

Talking of time, didn’t take the time to check the code yet. I’ll let you know if I find something.

**Comment by florentchandelier** [comment]
Dear gcamp, 
I have looked at my code and your comment.

Assuming 0% dividend, and <=0 capital appreciation, you will indeed get an improvements in mortgage repayment, that is relative to provincial and federal refund on the interest on capital borrowed to get investment ... if in qc then only federal refund applies.

At 0%div and <=0% appreciation, that is 20k refunds on a 450k mortgage, and 20k out of 360k (20% cash down) is almost 6% ... 

From my PoV this is as expected. As you said "Tax credit can't transform a loss into a gain", but Tax is not on the portfolio and dividends, it's on the interest and although it does not apply in provincial shreds if you're in qc, it will apply at the fed level even if you're in qc.

Nonetheless, once your house is repaid, you basically end up with a HELOC that equals your mortgage principal (360k), yet used to create a portfolio that did not appreciated (or depreciated) over time, and does not generate income (<= 360k).

When you say "we should see a results that's worst than a regular mortgage", what you should look at is not just "the mortgage", but your financial situation ... and you are in a much worst situation than just doing a regular mortgage ... in the end, you'll have repaid your mortgage about 3 or 4 years before (thanks to fed's refund at least), yet you'll need another about 25 years to repay the entire HELOC, adn you'll end up with a portfolio at least four times less than the HELOC value (considering over 50 yrs without appreication your value is killed by inflation) .... and do not forget HELOC interests are > mortgage interest.

So effectively, home will be repaid a little faster, but you are loosing money, due to HELOC interests, and capital depreciation ... as expected. I mean the cost of the SM is about that of the House (as provided by my script) ... a financial nightmare.

In essence, the code is about right, and the math as well ; it's not about the mortgage, it's about your entire financial situation ... Nonetheless I may have found a glitch in my code but I believe my comments above still hold, even without doing the math.

Thanks for reporting.
